#pragma once

#define LIGHTENCY_VERSION_MAJOR 1
#define LIGHTENCY_VERSION_MINOR 1
#define LIGHTENCY_VERSION_PATCH 2
#define LIGHTENCY_VERSION_BUILD 0

#define LIGHTENCY_RC_VERSION 1,1,2,0
#define LIGHTENCY_VERSION_STR "1.1.2"
#define LIGHTENCY_VERSION L"v1.1.2"
